### PR TITLE
Button to open the door on second level(#4)

### PR DESCRIPTION
**Pull request by 0lvin**

### CODE REVIEW

**Comment by 0lvin** [comment]
@k8wu @emileb Could you please check with such change?

**Comment by emileb** [comment]
I did a test on that button and it seems to work now. Just looking at the change did you mean to remove this code also?:

```
					if (j != i)
						continue;	// duplicated
```

We sure this isn't needed?

**Comment by k8wu** [comment]
Looks like it works for me. I was able to use a few more doors and lifts (both button-activated and not), and I encountered no problems.

**Comment by 0lvin** [comment]
I have little bit reverted changes with `if (j != i)`.

**Comment by Yamagi** [comment]
And merged. Thank you :)

**Pull request merged**
